name: Auto Push File

on:
  workflow_dispatch: 
    # 可以进行配置手动触发后有选项进行触发
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 */30 * *' # 每30天自动运行一次

jobs:
  push_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update File
        run: |
          # 获取当前时间戳
          timestamp=$(date +%s)
          # 更新文件的内容
          echo "This is an updated content. Timestamp: ${timestamp}" >> file.txt
      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add file.txt
          git commit -m "Auto update file.txt"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTOPUSH_TOKEN }}